definition
defineProperties
  super defineProperties.

  sPackage property: #name type: #String.
  sModule property: #name type: #String.
  operationSymbol property: #op type: #String.
  exception property: #name type: #String.
  exception property: #description type: #String.
  scope property: #id type: #String.
  declaration property: #name type: #String.
  asynchronable property: #isAsync type: #Boolean.
  parameter property: #name type: #String.
  sFunction property: #name type: #String.
  sFunction property: #isClassSide type: #Boolean.
  sClass property: #name type: #String.
  call property: #callee type: #String.
  varRef property: #name type: #String.
  attributeNav property: #attributeName type: #String.
  integer property: #value type: #Number.
  string property: #value type: #String.