definition
defineProperties

	super defineProperties.

	sPackage property: #name type: #String.
	sModule property: #name type: #String.
	operationSymbol property: #op type: #String.
	exception property: #name type: #String.
	exception property: #description type: #String.
	scope property: #id type: #String.
	asynchronable property: #isAsync type: #Boolean.
	parameter property: #name type: #String.
	sFunction property: #name type: #String.
	sFunction property: #isClassSide type: #Boolean.
	sClass property: #name type: #String